kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build-jitsi-web
  namespace: jitsi-dev
  uid: 573ca874-735f-4329-be8e-45642fb659ff
  resourceVersion: '4461991'
  generation: 2
  creationTimestamp: '2022-02-07T16:26:05Z'
  labels:
    name: docker-build-jitsi-web
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T16:15:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:name': {}
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T16:26:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jitsi-rossonet-web:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/rossonet/docker-jitsi-rossonet-meet.git'
    contextDir: /web
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/jitsi-dev/jitsi-rossonet-base@sha256:30935152f92ea954aaeec8ab6a2f0fb0b751c775ecc6f6cfb869f8a65161be6e
        from:
          kind: ImageStreamTag
          name: 'jitsi-rossonet-base:latest'
  runPolicy: Serial
status:
  lastVersion: 1
