kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build-jitsi-jibri
  namespace: jitsi-dev
  uid: e9035ff7-7f79-4430-a1f2-66709238e49a
  resourceVersion: '4459652'
  generation: 3
  creationTimestamp: '2022-02-07T16:15:48Z'
  labels:
    name: docker-build-jitsi-jibri
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T16:15:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:name': {}
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T16:19:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jitsi-rossonet-jibri:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/rossonet/docker-jitsi-rossonet-meet.git'
    contextDir: /jibri
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/jitsi-dev/jitsi-rossonet-base-java@sha256:0c0172d4a9d7ede0a2d1c9e4402a6df3863618a7be8061a9163d0b06809d9149
        from:
          kind: ImageStreamTag
          name: 'jitsi-rossonet-base-java:latest'
  runPolicy: Serial
status:
  lastVersion: 1
