kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build-jitsi-base-java
  namespace: jitsi-dev
  uid: 39c1e973-1c31-4a77-b1d7-568b8f2aa9af
  resourceVersion: '4452377'
  generation: 4
  creationTimestamp: '2022-02-07T15:51:07Z'
  labels:
    name: docker-build-jitsi-base-java
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T15:51:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:name': {}
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-07T15:58:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jitsi-rossonet-base-java:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/rossonet/docker-jitsi-rossonet-meet.git'
    contextDir: /base-java
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/jitsi-dev/jitsi-rossonet-base@sha256:bb0022ba4948d19b8e75fe91c5b33a8dde87287729ffdc22d7ed7c9dfb59b5c2
        from:
          kind: ImageStreamTag
          name: 'jitsi-rossonet-base:latest'
  runPolicy: Serial
status:
  lastVersion: 2
